language: python
python:
  - "3.10"  # Upgrade from 3.8 to 3.10 to support Django 5.1.6

install:
  - pip install -r requirements.txt  # Install dependencies

script:
  - black --check .  # Check code formatting
  - flake8 .  # Run linter
  - echo "Linting and formatting checks complete"
