language: python
dist: focal
python:
  - "3.10"

install:
  - pip install -r requirements.txt  # Install dependencies

script:
  - black --check .  # Check code formatting
  - flake8 .  # Run linter
  - coverage run --source='.' manage.py test  # Run tests with coverage

after_success:
  - coverage report  # Display coverage report in logs
  - coveralls  # Upload coverage report to Coveralls
